{
 "title": "Chia",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, instance)"
    }
   },
   {
    "name": "mounts",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "disks",
    "query": {
     "query": "label_values(node_disk_io_time_seconds_total, device)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_proofs_total)"
    }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_plots_total)",
     "legendFormat": "Plots"
    }
   ]
  },
  {
   "title": "$node CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\", instance=~\"$node.*\"}",
     "legendFormat": "CPU Temperature"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node.*\"} - node_filesystem_avail_bytes{instance=~\"$node.*\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Plot Production (avg 12 h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(chia_harvester_plots_total{instance=~\"$node.*\"}) - sum(chia_harvester_plots_total{instance=~\"$node.*\"} offset 12h)) /12 \n\n",
     "legendFormat": "Plots in the last 12h"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mojo" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_wallet_confirmed_balance_mojo"
    }
   ]
  },
  {
   "title": "Number of plots by instance",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_harvester_plots_total{instance=~\"192.168.1.22:[\\\\d]+\"}",
     "legendFormat": "plotter"
    },
    {
     "expr": "chia_harvester_plots_total{instance=~\"192.168.1.23:[\\\\d]+\"}",
     "legendFormat": "raspberry"
    },
    {
     "expr": "chia_harvester_plots_total{instance=~\"192.168.1.167:[\\\\d]+\"}",
     "legendFormat": "desktop"
    }
   ]
  },
  {
   "title": "Days till Win",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 / (sum(chia_harvester_plots_total) * 101.4 * 1.074e9 / on() chia_blockchain_space_bytes) )/ 4608",
     "legendFormat": "expected days untill win"
    }
   ]
  },
  {
   "title": "percentage of total netspace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(node_filesystem_size_bytes{mountpoint=~\"/home/tom/chia-plots/.*\"} ) - sum(node_filesystem_free_bytes{mountpoint=~\"/home/tom/chia-plots/.*\"}) + \nsum(node_filesystem_size_bytes{mountpoint=~ \"/home/joe/chia-dst.*\"} ) - sum(node_filesystem_free_bytes{mountpoint=~\"/home/joe/chia-dst.*\"})) / on() chia_blockchain_space_bytes) * 100",
     "legendFormat": "percentage of netspace"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node.*\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "chia_blockchain_space_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Disk Thoughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node.*\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node.*\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(chia_harvester_search_time_bucket[$__rate_interval])) by (le,plots_eligible))",
     "legendFormat": "{{plots_eligible}} Plots Passed Filter"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$node.*\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Total Plot Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(chia_harvester_plots_total) * 101.4 * 1.074e9"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node.*\"} - node_memory_MemFree_bytes{instance=~\"$node.*\"} - node_memory_Buffers_bytes{instance=~\"$node.*\"} - node_memory_Cached_bytes{instance=~\"$node.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node.*\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node.*\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_blockchain_sync_status", "legendFormat": "status" },
    {
     "expr": "chia_peers_count{type=\"1\"}",
     "legendFormat": "peers"
    },
    { "expr": "chia_blockchain_space_bytes", "legendFormat": "netspace" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$node.*\",mountpoint=~\"$mounts\"} - node_filesystem_avail_bytes{instance=~\"$node.*\",mountpoint=~\"$mounts\"}) / node_filesystem_size_bytes{instance=~\"$node.*\",mountpoint=~\"$mounts\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Usage (last 24hr)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node.*\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": " rx"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node.*\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Harvester Server Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{job=~\"chia-.*\"}|=\"harvester_server\""
    }
   ]
  },
  {
   "title": "Plotter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "{job=~\"plotter.*\"}!=\"uniform sort\""
    }
   ]
  },
  {
   "title": "Search Time Histogram (at least one plot passed filter)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_harvester_search_time_bucket{plots_eligible!=\"0\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Harvester Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "{job=~\"chia-.*\"}|=\"harvester.harvester\"|=\"WARNING\""
    }
   ]
  }
 ]
}